"""Add double puppet base URL to puppet table

Revision ID: 33078cd14618
Revises: 7d9a9a4d50d7
Create Date: 2020-10-26 13:44:49.576035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33078cd14618'
down_revision = '7d9a9a4d50d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('puppet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('base_url', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('puppet', schema=None) as batch_op:
        batch_op.drop_column('base_url')

    # ### end Alembic commands ###
